// next-headless/src/components/NavigationLinks.tsx
import { ILinks } from "types/interface";
import { useRouter } from "next/router";
import Link from "next/link";
import { useTranslation } from "react-i18next";

export const NavigationLinks = ({
  links,
  bold,
  color,
}: {
  links: ILinks["links"];
  bold: string;
  color: string;
}) => {
  const { pathname } = useRouter(),
    { t } = useTranslation();
  return (
    <>
      {links.map(({ route, dictionary }) => (
        <li key={dictionary}>
          <Link
            href={route}
            className={bold}
            style={{
              color: pathname == route ? "#000044" : color,
            }}
          >
            {dictionary ? t(dictionary) : ""}
          </Link>
        </li>
      ))}
    </>
  );
};

// nuxt-headless/components/NavigationLinks.vue
<template>
  <ul v-if="links.length" class="navigate_routes">
    <li v-for="{ route, dictionary } in links" :key="dictionary">
      <NuxtLink
        :class="bold"
        :style="{
          color: $route.path == route ? '#000044' : color,
        }"
        :to="route"
        >{{ $t(dictionary) }}</NuxtLink
      >
    </li>
  </ul>
</template>

<script>
export default {
  props: { links: [], bold: '', color: '' },
}
</script>
