// nuxt-headless/components/NavigationLinks.vue
<template>
  <ul v-if="links.length" class="navigate_routes">
    <li v-for="{ route, dictionary } in links" :key="dictionary">
      <NuxtLink
        :class="bold"
        :style="{
          color: $route.path == route ? '#000044' : color,
        }"
        :to="route"
        >{{ $t(dictionary) }}</NuxtLink
      >
    </li>
  </ul>
</template>

<script>
export default {
  props: { links: [], bold: '', color: '' },
}
</script>

// headless/src/components/NavigationLinks.tsx
import { Link, useLocation } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { ILinks } from 'types/interface'

export const NavigationLinks = ({
  links,
  bold,
  color,
}: {
  links: ILinks['links']
  bold: string
  color: string
}) => {
  const location = useLocation()
  const { t } = useTranslation()
  return (
    <>
      {links.map(({ route, dictionary }) => (
        <li key={dictionary}>
          <Link
            to={route}
            className={bold}
            style={{
              color: location.pathname == route ? '#000044' : color,
            }}
          >
            {dictionary ? t(dictionary) : ''}
          </Link>
        </li>
      ))}
    </>
  )
}
