// nuxt-headless/components/NavigationLinks.vue
<template>
  <ul v-if="links.length" class="navigate_routes">
    <li v-for="{ route, dictionary } in links" :key="dictionary">
      <NuxtLink
        :class="bold"
        :style="{
          color: $route.path == route ? '#000044' : color,
        }"
        :to="route"
        >{{ $t(dictionary) }}</NuxtLink
      >
    </li>
  </ul>
</template>

<script>
export default {
  props: { links: [], bold: '', color: '' },
}
</script>

// src/components/NavigationLinks.tsx
import { Link, useLocation } from 'react-router-dom'
import { useTranslation } from 'react-i18next'

export const NavigationLinks = ({ links, bold, color }) => {
  const { t } = useTranslation()
  return (
    <>
      {links.map(({ route, dictionary }) =>
        <li key={dictionary}>
          <Link
            to={route}
            className={bold}
            style={{
              color: useLocation().pathname == route
                ? '#000044'
                : color,
            }}
          >
            {t(dictionary)}
          </Link>
        </li>
      )}
    </>
  )
}
