// nuxt-headless/modals/MenuModal.vue
<template>
  <div
    :class="['base_modal_styles menu_modal_styles', $store.state.menuActive]"
    @click="
      (e) => e.target === e.currentTarget && $store.commit('unsetMenuModal')
    "
  >
    <nav class="relative shadow_radius">
      <CrossRed
        class="cross_icon absolute"
        @click="$store.commit('unsetMenuModal')"
      />
      <ul class="flex_center_bet_col center">
        <NavigationLinks :links="publicLinks" bold="b900" color="#737373" />
        <li :class="['login', $store.state.user ? 'signOut' : 'signIn']">
          <User :user="$store.state.user" styleName="menu_modal" />
        </li>
        <li class="buyСlass">
          <NuxtLink :to="RESERVE_ROUTE" class="flex_center_center b700 white">
            {{ $t('nav.buy') }}
          </NuxtLink>
        </li>
      </ul>
    </nav>
  </div>
</template>

<script lang="ts">
import CrossRed from '~/assets/icons/CrossRed.svg?inline'
import { publicLinks, RESERVE_ROUTE } from '~/constants/routes'

export default {
  name: 'MenuModal',
  components: {
    CrossRed,
  },
  data() {
    return {
      publicLinks,
      RESERVE_ROUTE,
    }
  },
}
</script>

<style lang="scss">
.menu_modal_styles {
  nav > ul {
    padding: 40px;
    li {
      width: 100%;
      max-width: 280px;
      a {
        display: inline-block;
        font-size: 20px;
        padding-top: 9.5px;
        padding-bottom: 9.5px;
        &:hover {
          color: #ff6376 !important;
        }
      }
      &.login {
        margin: 40px auto 20px;
      }
      &.buyСlass a {
        display: flex;
        box-sizing: border-box;
        height: 42px;
        border-radius: 32px;
        font-size: 14px;
        background-color: #59b894;
        transition: background-color 0.2s;
        &:hover {
          background-color: #000044;
        }
      }
    }
  }
}
</style>

// headless/src/modals/MenuModal.tsx
import { useContext, useMemo } from 'react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import styled from 'styled-components'
import { publicLinks, RESERVE_ROUTE } from 'constants/routes'
import { useAppDispatch, useAppSelector } from 'roothooks'
import { selectMenuModalActive, unsetMenuModal } from 'slices/modal.slice'
import { User } from 'components/User'
import { NavigationLinks } from 'components/NavigationLinks'
import { CrossRedSVG } from 'img/icons'
import { AppContext } from '../AppRouter'

export const BaseDiv = styled.div`
  opacity: 0;
  position: fixed;
  z-index: -99;
  left: 0;
  top: 0;
  width: 100%;
  // height: 200%;
  height: 100%;
  overflow: auto;
  background-color: rgba(0, 0, 0, 0.2);
  transition: opacity 0.4s, z-index 0.1s 0.4s;
  // @media (orientation: landscape) {
  //   height: 100%;
  // }
  @media (min-width: 1024px) {
    display: none;
  }
  nav {
    transform: scale(0);
    box-sizing: border-box;
    width: 90%;
    max-width: 480px;
    margin: 10vh auto;
    background: #fff;
    transition: transform 0.6s;
    .cross_icon {
      right: 15px;
      top: 15px;
      width: 24px;
      height: 24px;
      @media (hover: hover) {
        &:hover {
          cursor: pointer;
        }
      }
    }
  }
  &.menuActive,
  &.dashboarActive,
  &.loginActive,
  &.messageActive {
    z-index: 99;
    opacity: 1;
    transition: z-index 0.1s, opacity 0.4s 0.1s;
    nav {
      transform: scale(1);
    }
  }
`

const Div = styled(BaseDiv)`
  nav ul {
    padding: 40px;
    li {
      width: 100%;
      max-width: 280px;
      a {
        display: inline-block;
        font-size: 20px;
        padding-top: 9.5px;
        padding-bottom: 9.5px;
        &:hover {
          color: #ff6376 !important;
        }
      }
      &.login {
        margin: 40px auto 20px;
      }
      &.buyСlass a {
        display: flex;
        box-sizing: border-box;
        height: 42px;
        border-radius: 32px;
        font-size: 14px;
        background-color: #59b894;
        transition: background-color 0.2s;
        &:hover {
          background-color: #000044;
        }
      }
    }
  }
`

export const MenuModal = () => {
  const { t } = useTranslation()
  const { currentUser } = useContext(AppContext)
  const modalState = useAppSelector(selectMenuModalActive)
  const dispatch = useAppDispatch()
  // console.log('MenuModal: ')

  return (
    <Div
      className={modalState}
      onClick={(e) =>
        e.target === e.currentTarget && dispatch(unsetMenuModal())
      }
    >
      <nav className="relative shadow_radius">
        <CrossRedSVG
          className="cross_icon absolute"
          onClick={() => dispatch(unsetMenuModal())}
        />
        <ul className="flex_center_bet_col center">
          <NavigationLinks links={publicLinks} bold="b900" color="#737373" />
          <li className={'login ' + (currentUser ? 'signOut' : 'signIn')}>
            {/* {useMemo(
              () => (
                <User user={user} styleName="menu_modal" />
              ),
              [user]
            )} */}
            <User styleName="menu_modal" />
          </li>
          <li className="buyСlass">
            <Link to={RESERVE_ROUTE} className="flex_center_center b700 white">
              {t('nav.buy')}
            </Link>
          </li>
        </ul>
      </nav>
    </Div>
  )
}
